export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// import type { Metadata } from 'next'
 
// These styles apply to every route in the application
import './globals.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='dark'>{children}</body>
    </html>
  )
}
